export const CLIENT_FIELDS = [
  { key: 'company_name', label: 'Nazwa firmy' },
  { key: 'client_code_erp', label: 'Kod ERP' },
  { key: 'status', label: 'Status' },
  { key: 'data_veryfication', label: 'Weryfikacja danych' },
  { key: 'class_category', label: 'Kategoria klasy' },
  { key: 'street', label: 'Ulica' },
  { key: 'city', label: 'Miasto' },
  { key: 'postal_code', label: 'Kod pocztowy' },
  { key: 'voivodeship', label: 'Województwo' },
  { key: 'country', label: 'Kraj' },
  { key: 'nip', label: 'NIP' },
  { key: 'client_category', label: 'Kategoria klienta' },
  { key: 'client_subcategory', label: 'Podkategoria klienta' },
  { key: 'fairs', label: 'Targi' },
  { key: 'competition', label: 'Konkurencja' },
  { key: 'index_of_parent', label: 'ID nadrzędnego' },
  { key: 'engo_team_director', label: 'Dyrektor ENGO' },
  { key: 'engo_team_manager', label: 'Manager ENGO' },
  { key: 'engo_team_contact', label: 'Kontakt ENGO' },
  { key: 'engo_team_user_id', label: 'Użytkownik ENGO' },
  { key: 'engo_team_manager_user_id', label: 'Użytkownik Manager ENGO' },
  { key: 'engo_team_director_user_id', label: 'Użytkownik Dyrektor ENGO' },
  { key: 'number_of_branches', label: 'Liczba oddziałów' },
  { key: 'number_of_sales_reps', label: 'Liczba handlowców' },
  { key: 'www', label: 'WWW' },
  { key: 'possibility_www_baner', label: 'Możliwość banera WWW' },
  { key: 'possibility_add_articles', label: 'Możliwość dodania artykułów' },
  { key: 'facebook', label: 'Facebook' },
  { key: 'possibility_graphic_and_posts_FB', label: 'Grafika i posty FB' },
  { key: 'auction_service', label: 'Serwis aukcyjny' },
  { key: 'private_brand', label: 'Marka własna' },
  { key: 'private_brand_details', label: 'Szczegóły marki własnej' },
  { key: 'loyalty_program', label: 'Program lojalnościowy' },
  { key: 'loyalty_program_details', label: 'Szczegóły programu' },
  { key: 'turnover_pln', label: 'Obrót PLN' },
  { key: 'turnover_eur', label: 'Obrót EUR' },
  { key: 'installation_sales_share', label: 'Udział sprzedaży instalacji' },
  { key: 'automatic_sales_share', label: 'Udział sprzedaży automatyki' },
  { key: 'sales_potential', label: 'Potencjał sprzedaży' },
  { key: 'has_webstore', label: 'Sklep internetowy' },
  { key: 'has_ENGO_products_in_webstore', label: 'ENGO w sklepie' },
  { key: 'possibility_add_ENGO_products_to_webstore', label: 'Możliwość dodania ENGO do sklepu' },
  { key: 'has_b2b_platform', label: 'Platforma B2B' },
  { key: 'has_b2c_platform', label: 'Platforma B2C' },
  { key: 'additional_info', label: 'Dodatkowe informacje' },
  { key: 'structure_installer', label: 'Struktura: instalator' },
  { key: 'structure_wholesaler', label: 'Struktura: hurtownik' },
  { key: 'structure_ecommerce', label: 'Struktura: e-commerce' },
  { key: 'structure_retail', label: 'Struktura: retail' },
  { key: 'structure_other', label: 'Struktura: inne' },
  { key: 'latitude', label: 'Szerokość geogr.' },
  { key: 'longitude', label: 'Długość geogr.' },
]
