export const INSTALLER_FIELDS = [
  { key: 'company_name', label: 'Nazwa firmy' },
  { key: 'client_code_erp', label: 'Kod ERP' },
  { key: 'client_psmobile', label: 'PSMobile' },
  { key: 'status', label: 'Status' },
  { key: 'data_veryfication', label: 'Weryfikacja danych' },
  { key: 'class_category', label: 'Kategoria klasy' },
  { key: 'street', label: 'Ulica' },
  { key: 'city', label: 'Miasto' },
  { key: 'postal_code', label: 'Kod pocztowy' },
  { key: 'district', label: 'Powiat' },
  { key: 'voivodeship', label: 'Województwo' },
  { key: 'country', label: 'Kraj' },
  { key: 'nip', label: 'NIP' },
  { key: 'client_category', label: 'Kategoria klienta' },
  { key: 'client_subcategory', label: 'Podkategoria klienta' },
  { key: 'fairs', label: 'Targi' },
  { key: 'engo_team_director', label: 'Dyrektor ENGO' },
  { key: 'engo_team_manager', label: 'Manager ENGO' },
  { key: 'engo_team_contact', label: 'Kontakt ENGO' },
  { key: 'engo_team_user_id', label: 'Użytkownik ENGO' },
  { key: 'engo_team_manager_user_id', label: 'Użytkownik Manager ENGO' },
  { key: 'engo_team_director_user_id', label: 'Użytkownik Dyrektor ENGO' },
  { key: 'number_of_sales_reps', label: 'Liczba handlowców' },
  { key: 'www', label: 'WWW' },
  { key: 'facebook', label: 'Facebook' },
  { key: 'additional_info', label: 'Dodatkowe informacje' },
  { key: 'sms_consent', label: 'Zgoda SMS' },
  { key: 'marketing_consent', label: 'Zgoda marketingowa' },
  { key: 'source', label: 'Źródło' },
  { key: 'latitude', label: 'Szerokość geogr.' },
  { key: 'longitude', label: 'Długość geogr.' },
  { key: 'install_heating', label: 'Instalacje CO' },
  { key: 'install_AC', label: 'Klimatyzacje' },
  { key: 'install_ventilation', label: 'Wentylacje' },
  { key: 'install_sh', label: 'Sterowanie ogrzewaniem' },
  { key: 'koi_flats', label: 'KOI: mieszkania' },
  { key: 'koi_houses', label: 'KOI: domy' },
  { key: 'koi_OUP', label: 'KOI: OUP' },
  { key: 'koi_hotels', label: 'KOI: hotele' },
  { key: 'koi_comercial', label: 'KOI: komercyjne' },
  { key: 'koi_others', label: 'KOI: inne' },
  { key: 'numbers_of_subcontractors', label: 'Liczba podwykonawców' },
  { key: 'has_electrician', label: 'Ma elektryka' },
  { key: 'work_with_needs', label: 'Pracuje z potrzebami' },
  { key: 'approved_by_distributor', label: 'Zatwierdzony przez dystrybutora' },
  { key: 'problems_arrears', label: 'Zaległości' },
  { key: 'problem_time', label: 'Czas' },
  { key: 'problem_clients_with_inteligent_system', label: 'Klienci z inteligentnym systemem' },
  { key: 'problem_expensive', label: 'Drogo' },
  { key: 'problem_low_margin', label: 'Niska marża' },
  { key: 'problem_complicated_installation', label: 'Skomplikowana instalacja' },
  { key: 'problem_complicated_configuration', label: 'Skomplikowana konfiguracja' },
  { key: 'problem_app', label: 'Aplikacja' },
  { key: 'problem_support', label: 'Wsparcie' },
  { key: 'problem_complaint', label: 'Reklamacje' },
  { key: 'problem_training', label: 'Szkolenia' },
  { key: 'problem_integration', label: 'Integracje' },
  { key: 'problem_marketing_stuff', label: 'Materiały marketingowe' },
  { key: 'problem_competition', label: 'Konkurencja' },
  { key: 'problem_others', label: 'Inne problemy' },
]
